# Site
name: "Thich Cay Official"
description: "Authentic Vietnamese sauces & dressing."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "support@thichcay.com"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Thao:
    name: Thao
    site: https://www.thichcay.com
    avatar: /assets/images/avatar1.jpg
    bio: "Hi, I am Thao, the author of Thich Cay Sites, the theme you're currently previewing. I hope you like it!"
    email: thichcayvn@gmail.com
    twitter: https://twitter.com/thichcayvn

  Bao:
    name: Bao
    site: https://www.thichcay.com
    avatar: /assets/images/avatar2.jpg
    bio: "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    email: fakemail@gmail.com
    twitter: https://twitter.com/thichcayvn

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Thao
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
